-- Application schema for the job-application workflows (WF1-WF4).
--
-- Written from the SQL in the four workflows and checked by running every one
-- of those queries against it on PostgreSQL. It is not a dump of the original
-- installation, so column types and constraints may differ from that database.
--
-- Safe to run more than once: nothing existing is dropped or overwritten.
--
-- Usage (see docs/SETUP.md):
--   docker compose exec -T postgres psql -U n8n -d candidature -v ON_ERROR_STOP=1 < db/schema.sql

BEGIN;

-- Key/value state. WF1 keeps the Telegram getUpdates offset here.
CREATE TABLE IF NOT EXISTS bot_state (
    key   text PRIMARY KEY,
    value text NOT NULL
);

INSERT INTO bot_state (key, value)
VALUES ('tg_offset', '0')
ON CONFLICT (key) DO NOTHING;

-- One row per person applying. chat_id doubles as the Telegram allowlist:
-- WF1 ignores every chat that is not listed here.
CREATE TABLE IF NOT EXISTS applicants (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id           bigint  NOT NULL UNIQUE,
    sender_name       text    NOT NULL,
    phone             text,                      -- selected by WF4, not used in the email
    skeleton_file     text    NOT NULL,          -- container path of the LaTeX template
    email_sample_file text    NOT NULL,          -- container path of the email body
    cv_file           text    NOT NULL,          -- container path of the CV
    daily_limit       integer NOT NULL DEFAULT 10 CHECK (daily_limit >= 0),
    created_at        timestamptz NOT NULL DEFAULT now()
);

-- One row per employer and applicant. status drives the whole pipeline.
CREATE TABLE IF NOT EXISTS targets (
    id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id integer NOT NULL REFERENCES applicants (id) ON DELETE CASCADE,
    company      text    NOT NULL CHECK (btrim(company) <> ''),
    email        text    NOT NULL,
    email_domain text    NOT NULL,
    address      text,
    postcity     text,
    contact      text,                           -- HR contact name
    hr_email     text,
    status       text    NOT NULL DEFAULT 'new' CHECK (status IN (
                     'new', 'checking', 'email_found', 'no_email',
                     'drafting', 'awaiting_approval', 'queued', 'sending',
                     'sent', 'replied', 'skipped', 'stop', 'error')),
    mx_ok        boolean,
    subject      text,
    email_body   text,
    letter_pdf   text,                           -- container path of the compiled letter
    error        text,
    attempts     integer NOT NULL DEFAULT 0,     -- incremented by "Refaire"
    approved_at  timestamptz,
    sent_at      timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);

-- Duplicate rules. The inserts in WF1 use ON CONFLICT DO NOTHING, and the bot
-- then answers "existe déjà (même nom ou même domaine email)". These two
-- indexes implement exactly that message.
CREATE UNIQUE INDEX IF NOT EXISTS targets_applicant_company_key
    ON targets (applicant_id, lower(company));

-- This one also blocks two different employers that share a mail provider
-- (two companies both writing from gmail.com, for example). Drop it if that
-- matters to you:  DROP INDEX targets_applicant_domain_key;
CREATE UNIQUE INDEX IF NOT EXISTS targets_applicant_domain_key
    ON targets (applicant_id, email_domain);

-- The workers claim rows by status in id order; WF4 also orders by approved_at.
CREATE INDEX IF NOT EXISTS targets_status_id_idx ON targets (status, id);

-- Dialog state of the guided entry, one row per chat. WF1 upserts on chat_id.
CREATE TABLE IF NOT EXISTS conversations (
    chat_id    bigint PRIMARY KEY,
    step       text  NOT NULL DEFAULT 'done',
    data       jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
